# Generated by Django 4.2.6 on 2023-10-28 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShopingCart",
            new_name="ShoppingCart",
        ),
    ]
