# Generated by Django 4.2.6 on 2023-11-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_rename_shopingcart_shoppingcart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ("id",),
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": ("id",),
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзина",
            },
        ),
    ]
